In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from keras.utils import np_utils
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Dense, Flatten
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import load_model
from PIL import Image, ImageOps
import numpy

In [17]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [18]:
print(X_train.shape)
print(X_test.shape)

(60000, 28, 28)
(10000, 28, 28)


In [19]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [20]:
y_train[2]

4

In [21]:
X_train = X_train.reshape(60000, 28, 28, 1).astype('float32')
X_test = X_test.reshape(10000, 28, 28, 1).astype('float32')

In [27]:
number_of_classes = 10
Y_train = np_utils.to_categorical(y_train, number_of_classes)
Y_test = np_utils.to_categorical(y_test, number_of_classes)

In [29]:
Y_train[2]

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

In [30]:
model = Sequential()
model.add(Conv2D(64, (3, 3), input_shape=(28, 28, 1), activation="relu"))
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(Flatten())
model.add(Dense(number_of_classes, activation="softmax"))

In [31]:
model.compile(loss='categorical_crossentropy', optimizer="Adam", metrics=["accuracy"])

In [32]:
model.fit(X_train, Y_train, batch_size=32, epochs=5, validation_data=(X_test,Y_test))

Epoch 1/5
1875/1875 [==============================] - 187s 99ms/step - loss: 0.2899 - accuracy: 0.9489 - val_loss: 0.0776 - val_accuracy: 0.9751
Epoch 2/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.0705 - accuracy: 0.9786 - val_loss: 0.0861 - val_accuracy: 0.9759
Epoch 3/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.0446 - accuracy: 0.9861 - val_loss: 0.0785 - val_accuracy: 0.9782
Epoch 4/5
1875/1875 [==============================] - 187s 100ms/step - loss: 0.0358 - accuracy: 0.9885 - val_loss: 0.0930 - val_accuracy: 0.9754
Epoch 5/5
1875/1875 [==============================] - 184s 98ms/step - loss: 0.0252 - accuracy: 0.9922 - val_loss: 0.1171 - val_accuracy: 0.9764


In [33]:
metrics = model.evaluate(X_test, Y_test, verbose=0)
print("Metrics (Test Loss & Test Accuracy): ")
print(metrics)

Metrics (Test Loss & Test Accuracy): 
[0.11714021861553192, 0.9764000177383423]


In [34]:
prediction = model.predict(X_test[:4])
print(prediction)

1/1 [==============================] - 0s 89ms/step
[[1.1237912e-12 4.5514278e-16 3.7057896e-07 3.4224119e-09 3.8771159e-21
  7.8677931e-16 5.0402027e-23 9.9999964e-01 3.6511708e-14 3.6360938e-12]
 [2.0185852e-14 3.0416181e-13 1.0000000e+00 5.5697759e-13 8.1488266e-22
  5.6555627e-22 3.8230080e-08 1.2797922e-20 7.3457906e-11 6.4836394e-22]
 [2.9487361e-12 1.0000000e+00 2.0548809e-09 6.9894423e-15 4.4705675e-10
  3.4257525e-08 1.4304028e-11 2.0556119e-11 2.8342566e-09 8.5131258e-15]
 [1.0000000e+00 3.0372215e-22 5.6292831e-14 1.2220577e-20 1.1264333e-16
  5.2888575e-14 9.4831110e-10 8.7399935e-19 1.6402063e-14 3.4596041e-14]]


In [35]:
print(numpy.argmax(prediction, axis=1))
print(Y_test[:4])

[7 2 1 0]
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
model.save("model.h5")